In [2]:
import numpy as np

# Given array
original_array = np.array([1, 2, 3,4])

# Number of times to repeat
repeat_times = 3

# Constructing the array by repeating the given array
constructed_array = np.tile(original_array, repeat_times)

print("Original Array:", original_array)
print("Constructed Array:", constructed_array)


Original Array: [1 2 3 4]
Constructed Array: [1 2 3 4 1 2 3 4 1 2 3 4]


In [5]:
import numpy as np
array = np.array(['Python', 'PHP', 'JS', 'examples', 'html'])
lowercase_array = np.char.lower(array)
count_p = np.char.count(lowercase_array, 'p')
print("Original Array:")
print(array)
print("Number of 'p':")
print(count_p)

Original Array:
['Python' 'PHP' 'JS' 'examples' 'html']
Number of 'p':
[1 2 0 1 0]


In [6]:
import numpy as np

# Create an array
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Compute mean along the second axis
mean = np.mean(array, axis=1)

# Compute standard deviation along the second axis
std_deviation = np.std(array, axis=1)

# Compute variance along the second axis
variance = np.var(array, axis=1)

print("Array:")
print(array)
print("Mean along the second axis:")
print(mean)
print("Standard deviation along the second axis:")
print(std_deviation)
print("Variance along the second axis:")
print(variance)

Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Mean along the second axis:
[2. 5. 8.]
Standard deviation along the second axis:
[0.81649658 0.81649658 0.81649658]
Variance along the second axis:
[0.66666667 0.66666667 0.66666667]


In [7]:
import numpy as np

# Sample arrays (corrected)
array1 = np.array([[0, 1, 3],
                   [5, 7, 9]])

array2 = np.array([[0, 2, 4],
                   [6, 8, 10]])

# Concatenate arrays and reshape them to match the expected output
result = np.concatenate((array1, array2), axis=1).reshape(2, -1)

print("Concatenated array:")
print(result)

Concatenated array:
[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


In [10]:
import numpy as np

# Create sample arrays
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

# Arithmetic operations
print("Addition:", np.add(a, b))
print("Subtraction:", np.subtract(a, b))
print("Multiplication:", np.multiply(a, b))
print("Division:", np.divide(a, b))

# Trigonometric functions
angles = np.array([0, np.pi/2, np.pi])
print("Sine:", np.sin(angles))
print("Cosine:", np.cos(angles))
print("Tangent:", np.tan(angles))

# Exponential and logarithmic functions
print("Exponential:", np.exp(a))
print("Natural logarithm:", np.log(a))
print("Base 10 logarithm:", np.log10(a))

# Other ufuncs
print("Square root:", np.sqrt(a))
print("Absolute values:", np.absolute([-1, -2, 3, -4]))
print("Rounding:", np.round([1.2,2.5,3.7]))

Addition: [ 6  8 10 12]
Subtraction: [-4 -4 -4 -4]
Multiplication: [ 5 12 21 32]
Division: [0.2        0.33333333 0.42857143 0.5       ]
Sine: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Cosine: [ 1.000000e+00  6.123234e-17 -1.000000e+00]
Tangent: [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]
Exponential: [ 2.71828183  7.3890561  20.08553692 54.59815003]
Natural logarithm: [0.         0.69314718 1.09861229 1.38629436]
Base 10 logarithm: [0.         0.30103    0.47712125 0.60205999]
Square root: [1.         1.41421356 1.73205081 2.        ]
Absolute values: [1 2 3 4]
Rounding: [1. 2. 4.]


In [11]:
import numpy as np

# Create a vector with values from 0 to 20
vector = np.arange(21)

# Change the sign of numbers in the range from 9 to 15
vector[9:16] *= -1

print("Original vector:")
print(vector)

Original vector:
[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [13]:
import numpy as np

# Given array
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Sum of all elements
total_sum = np.sum(array)

# Sum of each column
column_sum = np.sum(array, axis=0)

# Sum of each row
row_sum = np.sum(array, axis=1)

print("Given array:")
print(array)
print("Sum of all elements:",total_sum)
print("Sum of each column:",column_sum)
print("Sum of each row:",row_sum)

Given array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Sum of all elements: 45
Sum of each column: [12 15 18]
Sum of each row: [ 6 15 24]


In [14]:
import numpy as np

# Define two arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([4, 5, 6, 7, 8])

# Union
union = np.union1d(array1, array2)

# Intersection
intersection = np.intersect1d(array1, array2)

# Difference (elements in array1 but not in array2)
difference = np.setdiff1d(array1, array2)

# Symmetric difference (elements that are in either of the arrays but not in both)
symmetric_difference = np.setxor1d(array1, array2)

print("Array 1:", array1)
print("Array 2:", array2)
print("Union:", union)
print("Intersection:", intersection)
print("Difference (array1 - array2):", difference)
print("Symmetric Difference:", symmetric_difference)

Array 1: [1 2 3 4 5]
Array 2: [4 5 6 7 8]
Union: [1 2 3 4 5 6 7 8]
Intersection: [4 5]
Difference (array1 - array2): [1 2 3]
Symmetric Difference: [1 2 3 6 7 8]


In [15]:
How to create a series from a list, numpy array and dict?

Init signature: dict(self, /, *args, **kwargs)
Docstring:     
dict() -> new empty dictionary
dict(mapping) -> new dictionary initialized from a mapping object's
    (key, value) pairs
dict(iterable) -> new dictionary initialized as if via:
    d = {}
    for k, v in iterable:
        d[k] = v
dict(**kwargs) -> new dictionary initialized with the name=value pairs
    in the keyword argument list.  For example:  dict(one=1, two=2)
Type:           type
Subclasses:     OrderedDict, defaultdict, Counter, _EnumDict, _Quoter, _QByteMap, SelectableGroups, _Meta_1_0, _Meta_1_1, _OptionalProjectFileDetails_1_0, ...


In [16]:
import pandas as pd
import numpy as np

my_array = np.array([10, 20, 30, 40, 50])
series_from_array = pd.Series(my_array)
print("Series from NumPy array:")
print(series_from_array)

my_dict = {'a': 10, 'b': 20, 'c': 30, 'd': 40, 'e': 50}
series_from_dict = pd.Series(my_dict)
print("Series from dictionary:")
print(series_from_dict)

my_list = [10, 20, 30, 40, 50]
series_from_list = pd.Series(my_list)
print("Series from list:")
print(series_from_list)


Series from NumPy array:
0    10
1    20
2    30
3    40
4    50
dtype: int32
Series from dictionary:
a    10
b    20
c    30
d    40
e    50
dtype: int64
Series from list:
0    10
1    20
2    30
3    40
4    50
dtype: int64


In [17]:
import numpy as np

# Create an identity array
identity_array = np.identity(3)  # Create a 3x3 identity array
print("Identity Array:")
print(identity_array)

# Create a diagonal array
diagonal_array = np.diag([1, 2, 3, 4])  # Create a diagonal array with the specified diagonal elements
print("\nDiagonal Array:")
print(diagonal_array)

Identity Array:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Diagonal Array:
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [18]:
import numpy as np

# Create a 2D array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Basic slicing: extracting a subarray
subarr = arr[0:2, 1:3]  # Rows 0 to 1, Columns 1 to 2
print("Subarray:")
print(subarr)

# Slicing with steps
subarr_step = arr[::2, ::2]  # Every other row, every other column
print("\nSubarray with steps:")
print(subarr_step)

# Slicing to extract a column
column = arr[:, 1]  # All rows, column 1
print("\nColumn:")
print(column)

# Slicing to extract a row
row = arr[1, :]  # Row 1, all columns
print("\nRow:")
print(row)

Subarray:
[[2 3]
 [5 6]]

Subarray with steps:
[[1 3]
 [7 9]]

Column:
[2 5 8]

Row:
[4 5 6]


In [19]:
import numpy as np

# Create sample arrays
array1 = np.array([[1, 2, 3],
                    [4, 5, 6]])

array2 = np.array([[7, 8, 9],
                    [10, 11, 12]])

# Joining along an existing axis (axis=1, columns)
joined_array = np.concatenate((array1, array2), axis=1)

# Stacking to create a new axis (axis=0, new rows)
stacked_array = np.stack((array1, array2))

print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)
print("\nJoined array:")
print(joined_array)
print("\nStacked array:")
print(stacked_array)

Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[ 7  8  9]
 [10 11 12]]

Joined array:
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]

Stacked array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
